---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 5-demo-source-helm-release-git-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-git-bb-app
  interval: 10s
  targetNamespace: 5-demo
  values:
    namespace:
      name: 5-demo
    replicaCount: 2
    service:
      nodePort: 30005
      type: NodePort
